export const employees = [
  {
    id: 1,
    name: "Safae Belhaj",
    position: "Manager",
    age: 35,
    startDate: "2020-02-15",
  },
  {
    id: 2,
    name: "Erika Musterfrau",
    position: "Supervisor",
    age: 42,
    startDate: "2018-09-10",
  },
  {
    id: 3,
    name: "Hans Müller",
    position: "Developer",
    age: 28,
    startDate: "2021-07-01",
  },
  {
    id: 4,
    name: "Lisa Schmidt",
    position: "Designer",
    age: 31,
    startDate: "2019-05-03",
  },
  {
    id: 5,
    name: "Peter Schulz",
    position: "Sales Representative",
    age: 37,
    startDate: "2020-11-20",
  },
  {
    id: 6,
    name: "Sarah Meier",
    position: "Marketing Specialist",
    age: 29,
    startDate: "2021-01-05",
  },
  {
    id: 7,
    name: "Thomas Fischer",
    position: "Accountant",
    age: 40,
    startDate: "2017-03-12",
  },
  {
    id: 8,
    name: "Laura Keller",
    position: "Human Resources",
    age: 33,
    startDate: "2018-06-08",
  },
  {
    id: 9,
    name: "Janine Wagner",
    position: "Customer Support",
    age: 27,
    startDate: "2022-03-01",
  },
  {
    id: 10,
    name: "Markus Becker",
    position: "IT Administrator",
    age: 45,
    startDate: "2016-09-30",
  },
];
